pygments: true
auto: true

title: Where Does My Money Go?
openspendingjs: 'http://openspending.org/static/openspendingjs'
baseurl: '/wheredoesmymoneygo.org'
dataset: 'segob_fonden'
timecut: 'time.year:2013'

